// ui/settings/field/boolean.jsx
'use strict'

const React = require('react')
const PropTypes = require('prop-types')

exports.BooleanField = function BooleanField (props) {
  return <label>
    {props.display || props.name}
    <input
      type={`checkbox`}
      name={props.name}
      checked={props.value}
      onChange={e => props.onValueChange(e.target.checked)}
    />
    <br/>
  </label>
}

exports.BooleanField.propTypes = {
  name: PropTypes.string,
  display: PropTypes.string,
  value: PropTypes.string,
  min: PropTypes.number,
  max: PropTypes.number,
  onValueChange: PropTypes.func
}

// src/renderer/components/settings/field/boolean.vue
<template>
  <label>
    {{ field.display || field.name }}
    <input
      type="checkbox"
      :name="field.name"
      :checked="value"
      @change="$emit('value-change', $event.target.checked)"
    />
  </label>
</template>

<script>
  export default {
    name: 'boolean-field',
    props: ['field', 'value']
  }
</script>

<style scoped>

</style>
