// ui/settings/field/index.jsx
'use strict'

const React = require('react')
const PropTypes = require('prop-types')

const { IntegerField } = require('./integer')
const { DecimalField } = require('./decimal')
const { BooleanField } = require('./boolean')
const { StringField } = require('./string')
const { ValuesField } = require('./values')

class Field extends React.Component {
  render () {
    switch (this.props.type) {
      case 'integer':
        return <IntegerField {...this.props}/>
      case 'decimal':
        return <DecimalField {...this.props}/>
      case 'boolean':
        return <BooleanField {...this.props}/>
      case 'string':
        return <StringField {...this.props}/>
      case 'values':
        return <ValuesField {...this.props}/>
      default:
        return <span><b>Error</b>{this.props.name}</span>
    }
  }
}

Field.propTypes = {
  type: PropTypes.string,
  name: PropTypes.string,
  onValueChange: PropTypes.func
}

exports.Field = Field

// src/renderer/components/settings/field/index.vue
<template>
  <div v-if="fieldComponent">
    <component :is="fieldComponent" v-bind="{ field, value }" @value-change="v => $emit('value-change', v)" />
  </div>
</template>

<script>
  import IntegerField from './integer'
  import DecimalField from './decimal'
  import BooleanField from './boolean'
  import StringField from './string'
  import ValuesField from './values'

  export default {
    name: 'index',
    props: ['field', 'value'],
    components: {
      IntegerField
    },
    data () {
      let fieldComponent = null

      switch (this.field.type) {
        case 'integer':
          fieldComponent = IntegerField
          break
        case 'boolean':
          fieldComponent = BooleanField
          break
        case 'decimal':
          fieldComponent = DecimalField
          break
        case 'string':
          fieldComponent = StringField
          break
        case 'values':
          fieldComponent = ValuesField
          break
      }

      return {
        fieldComponent
      }
    }
  }
</script>

<style scoped>

</style>
