// ui/settings/field/values.jsx
'use strict'

const React = require('react')
const PropTypes = require('prop-types')

exports.ValuesField = function ValuesField (props) {
  return <div>
    <span>{props.display || props.name}</span>
    {props.values.map(v => <label key={v}>
      <input
        type={`radio`}
        name={props.name}
        value={v}
        checked={props.value === v}
        onChange={e => props.onValueChange(e.target.value)}
      /> {v}
    </label>)}
  </div>
}

exports.ValuesField.propTypes = {
  name: PropTypes.string,
  display: PropTypes.string,
  value: PropTypes.string,
  values: PropTypes.arrayOf(PropTypes.string),
  onValueChange: PropTypes.func
}

// src/renderer/components/settings/field/values.vue
<template>
    <div>
        {{ field.display || field.name }}:
        <label v-for="v in field.values">
        <input
            type="radio"
            :name="field.name"
            :value="v"
            :checked="value === v"
            @change="$event.target.checked && $emit('value-change', $event.target.value)"
        /> {{ v }}
    </label>
    </div>
</template>

<script>
  export default {
    name: 'values-field',
    props: ['field', 'value']
  }
</script>

<style scoped>

</style>
