// ui/settings/index.jsx
'use strict'

const React = require('react')
const { Switch, Route } = require('react-router')
const electron = require('electron')

const { SettingsMenu } = require('./menu')
const { ModuleSettings } = require('./module')

class Settings extends React.Component {
  constructor (props) {
    super(props)
    this.adapter = electron.remote.require('./main').settingsAdapter

    this.adapter.getModulesNames((err, modulesNames) => {
      if (err) {
        console.error(err)
        return
      }

      this.setState({ modules: modulesNames })
    })

    this.state = {
      modules: []
    }
  }

  render () {
    return <div>
      <h1>Settings</h1>
      <SettingsMenu modules={this.state.modules} />
      <Switch>
        <Route exact path={`/settings`} />
        <Route path={`/settings/:module`}
          render={({ match }) => <ModuleSettings name={match.params.module} />} />
      </Switch>
    </div>
  }
}

exports.Settings = Settings

// src/renderer/components/settings/index.vue
<template>
    <div>
        <h1>Settings</h1>
        <SettingsMenu :modules="modules" />
        <router-view></router-view>
    </div>
</template>

<script>
  import SettingsMenu from './menu'

  export default {
    name: 'settings',
    components: { SettingsMenu },
    data () {
      return {
        modules: []
      }
    },
    mounted () {
      const adapter = this.$electron.remote.require('./main').settingsAdapter

      adapter.getModulesNames((err, modulesNames) => {
        if (err) {
          console.error(err)
          return
        }

        this.modules = modulesNames
      })
    }
  }
</script>

<style scoped>

</style>
