// ui/settings/menu.jsx
'use strict'

const React = require('react')
const PropTypes = require('prop-types')

const { NavLink } = require('react-router-dom')

class SettingsMenu extends React.Component {
  render () {
    return this.props.modules
      .map(name => <NavLink key={name}
        to={`/settings/${name}`}
        activeStyle={{ 'font-weight': 'bold' }}>{name}
      </NavLink>)
  }
}

SettingsMenu.propTypes = {
  modules: PropTypes.arrayOf(PropTypes.string)
}

exports.SettingsMenu = SettingsMenu

// src/renderer/components/settings/menu.vue
<template>
  <div>
      <router-link v-for="module in modules" :to="{ name: 'settings-module', params: { module } }" :key="module">
          {{ module }}
      </router-link>
  </div>
</template>

<script>
  export default {
    name: 'settings-menu',
    props: [ 'modules' ]
  }
</script>

<style scoped>
  .router-link-active {
    font-weight: bold
  }
</style>
