// src/renderer/components/settings/field/decimal.vue
<template>
    <label>
        {{ field.display || field.name }}
        <input
            type="number"
            :name="field.name"
            :value="field.value"
            :min="field.min"
            :max="field.max"
        />
    </label>
</template>

<script>
  export default {
    name: 'decimal-field',
    props: ['field', 'value']
  }
</script>

<style scoped>

</style>

// ui/settings/field/decimal.jsx
'use strict'

const React = require('react')
const PropTypes = require('prop-types')

exports.DecimalField = function DecimalField (props) {
  return <label>
    {props.display || props.name}
    <input
      type={`number`}
      name={props.name}
      value={props.value}
      min={props.min}
      max={props.max}
      onChange={e => props.onValueChange(e.target.value)}
    />
    <br/>
  </label>
}

exports.DecimalField.propTypes = {
  name: PropTypes.string,
  display: PropTypes.string,
  value: PropTypes.string,
  min: PropTypes.number,
  max: PropTypes.number,
  onValueChange: PropTypes.func
}
