// src/renderer/components/settings/field/integer.vue
<template>
  <label>
    {{ field.display || field.name }}
    <input
      type="number"
      :name="field.name"
      :value="value"
      :min="field.min"
      :max="field.max"
      @change="$emit('value-change', $event.target.value)"
    />
  </label>
</template>

<script>
  export default {
    name: 'integer-field',
    props: ['field', 'value']
  }
</script>

<style scoped>

</style>

// ui/settings/field/integer.jsx
'use strict'

const React = require('react')
const PropTypes = require('prop-types')

exports.IntegerField = function IntegerField (props) {
  return <label>
    {props.display || props.name}
    <input
      type={`number`}
      name={props.name}
      value={props.value}
      min={props.min}
      max={props.max}
      onChange={e => props.onValueChange(e.target.value)}
    />
    <br/>
  </label>
}

exports.IntegerField.propTypes = {
  name: PropTypes.string,
  display: PropTypes.string,
  value: PropTypes.string,
  min: PropTypes.number,
  max: PropTypes.number,
  onValueChange: PropTypes.func
}
